version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-cargo-lock-{{ checksum "Cargo.lock" }}

      - run: cargo test
      - run: cargo build --all --all-targets

      - save_cache:
          key: v1-cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - target
