version: 2
jobs:
  build:
    docker:
      - image: mmmpa/rust_wasm_node:latest

    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export PATH=$PATH:$HOME/node/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin' >> $BASH_ENV
            source $BASH_ENV

      - checkout
      - restore_cache:
          key: project-cache

      - run: cargo test
      - run: wasm-pack build --release

      - run: cd www && yarn install
      - run: cd pkg && ln -s ../www/node_modules node_modules
      - run: cd www && yarn lint
      - run: cd www && yarn build

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
            - "./dist"
            - "./www/node_modules"
